#pragma once

#include <vector>
#include <string>

namespace CheckFileSys {

    /**
     * Check specific flags of QEMU (Android Studio's core emulator).
     */
    bool hasQemuPipes(std::vector<std::string>& evidences);

    /**
     * Check files which generated by Genymotion.
     */
    bool hasGenymotionFiles(std::vector<std::string>& evidences);

    /**
     * Check files which generated by other emulators (BlueStacks, Andy, Droid4X,...).
     */
    bool hasSuspiciousFiles(std::vector<std::string>& evidences);
};